<?php

/**
 * This is the model class for table "auto_chores".
 *
 * The followings are the available columns in table 'auto_chores':
 * @property integer $auto_chores_id
 * @property string $description
 * @property integer $times_occur
 * @property integer $days_between
 * @property string $generated_by
 * @property string $date_asof
 * @property integer $days_after
 * @property integer $farm_herd
 * @property integer $disabled
 * @property string $date_modified
 */
class AutoChores extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return AutoChores the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'auto_chores';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('description, times_occur, days_between, generated_by, date_asof, days_after, farm_herd', 'required'),
			array('times_occur, days_between, days_after', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>25),
			array('generated_by', 'length', 'max'=>20),
			array('date_asof', 'length', 'max'=>10),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('auto_chores_id, description, times_occur, days_between, generated_by, date_asof, days_after, farm_herd, disabled, date_modified', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'auto_chores_id' => 'Auto Chores',
			'description' => 'Description',
			'times_occur' => 'Times Occur',
			'days_between' => 'Days Between',
			'generated_by' => 'Generated By',
			'date_asof' => 'Date Asof',
			'days_after' => 'Days After',
			'farm_herd' => 'Farm Herd',
			'disabled' => 'Disabled',
			'date_modified' => 'Date Modified',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('auto_chores_id',$this->auto_chores_id);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('times_occur',$this->times_occur);
		$criteria->compare('days_between',$this->days_between);
		$criteria->compare('generated_by',$this->generated_by,true);
		$criteria->compare('date_asof',$this->date_asof,true);
		$criteria->compare('days_after',$this->days_after);
		$criteria->compare('farm_herd',$this->farm_herd);
		$criteria->compare('disabled',$this->disabled);
		$criteria->compare('date_modified',$this->date_modified,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}