<?php
/* @var $this AutoChoresController */
/* @var $model AutoChores */
/* @var $form CActiveForm */
?>


<div class="form">

<?php
$form=$this->beginWidget('CActiveForm', array(
	'id'=>'auto-chores-form',
	'enableAjaxValidation'=>false,
));
echo "COUNT".$count = $dataProvider->itemCount;
$names = array();
?>
<div class="grid-view" id="container">
<table class="items">
<thead>
<tr>
<th id="sow-gilts-grid_c0">Description</th>
<th id="sow-gilts-grid_c1">Times to occur</th>
<th id="sow-gilts-grid_c2">Days Between</th>
<th id="sow-gilts-grid_c3">Generated By</th>
<th id="sow-gilts-grid_c4">As of Date</th>
<th id="sow-gilts-grid_c5">Days After</th>
<th id="sow-gilts-grid_c6">Farm & Herd</th>
<th id="sow-gilts-grid_c6"></th>
</tr>
</thead>
<tbody>
<?php
foreach($dataProvider->getData() as $record) {
?>
<tr class="odd hasmenu" id="<?php echo $record->auto_chores_id; ?>">
<td id="<?php echo $record->auto_chores_id."_desc"; ?>"><?php echo $record->description; ?></td>
<td id="<?php echo $record->auto_chores_id."_times"; ?>"><?php echo $record->times_occur; ?></td>
<td id="<?php echo $record->auto_chores_id."_days"; ?>"><?php echo $record->days_between; ?></td>
<td id="<?php echo $record->auto_chores_id."_generated"; ?>"><?php echo $record->generated_by; ?></td>
<td id="<?php echo $record->auto_chores_id."_date"; ?>"><?php echo $record->date_asof; ?></td>
<td id="<?php echo $record->auto_chores_id."_after"; ?>"><?php echo $record->days_after; ?></td>
<td id="<?php echo $record->auto_chores_id."_farm"; ?>"><?php echo $record->farm_herd; ?></td>
<td id="<?php echo $record->auto_chores_id."_disabled"; ?>"><?php echo ($record->disabled == 'Y')?"Disabled":""; ?></td>
</tr>

<?php
}
?>

<tr class="odd" id="insertrow">
	<?php echo $form->errorSummary($model); ?>

	<td id="descinsert">
		<?php echo $form->textField($model,'description',array('size'=>25,'maxlength'=>25)); ?>
		<?php echo $form->error($model,'description'); ?>
	</td>

	<td  id="timesinsert">
		<?php echo $form->textField($model,'times_occur',array('size'=>2,'maxlength'=>2)); ?>
		<?php echo $form->error($model,'times_occur'); ?>
	</td>

	<td  id="daysinsert">
		<?php echo $form->textField($model,'days_between'); ?>
		<?php echo $form->error($model,'days_between',array('size'=>3,'maxlength'=>3)); ?>
	</td>

	<td  id="generatedinsert">
		<?php //echo $form->textField($model,'generated_by',array('size'=>1,'maxlength'=>1)); ?>
		<?php echo $form->dropDownList($model,'generated_by',array('B'=>'B','F'=>'F','W'=>'W','D'=>'D'),
				array('size'=>0));
		?>
		<?php echo $form->error($model,'generated_by'); ?>
	</td>

	<td  id="dateinsert">
		<?php echo $form->textField($model,'date_asof',array('size'=>10,'maxlength'=>10)); ?>
		<?php echo $form->error($model,'date_asof'); ?>
	</td>

	<td  id="daysinsert">
		<?php echo $form->textField($model,'days_after',array('size'=>3,'maxlength'=>3)); ?>
		<?php echo $form->error($model,'days_after'); ?>
	</td>

	<td  id="farminsert">
		<?php echo $form->textField($model,'farm_herd',array('size'=>2,'maxlength'=>2)); ?>
		<?php echo $form->error($model,'farm_herd'); ?>
	</td>
	<td>
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</td>
</tr>
</tbody>
</table>
</div>

<?php $this->endWidget(); ?>

</div><!-- form -->