<?php
/* @var $this AutoChoresController */
/* @var $model AutoChores */
/* @var $form CActiveForm */
?>


<div class="form">

<?php
$form=$this->beginWidget('CActiveForm', array(
	'id'=>'auto-chores-form',
	'enableAjaxValidation'=>false,
));
echo "COUNT".$count = $dataProvider->itemCount;
$names = array();
print_r($dataProvider->getData());

 ?>
<div class="grid-view" id="sow-gilts-grid">
<table class="items">
<thead>
<tr>
<th id="sow-gilts-grid_c0">Description</th>
<th id="sow-gilts-grid_c1">Times to occur</th>
<th id="sow-gilts-grid_c2">Days Between</th>
<th id="sow-gilts-grid_c3">Generated By</th>
<th id="sow-gilts-grid_c4">As of Date</th>
<th id="sow-gilts-grid_c5">Days After</th>
<th id="sow-gilts-grid_c6">Farm & Herd</th>
<th id="sow-gilts-grid_c6"></th>
</tr>
</thead>
<tbody>
<?php
foreach($dataProvider->getData() as $record) {
?>
<tr class="odd">
<td><?php echo $record->description; ?></td>
<td><?php echo $record->times_occur; ?></td>
<td><?php echo $record->days_between; ?></td>
<td><?php echo $record->generated_by; ?></td>
<td><?php echo $record->date_asof; ?></td>
<td><?php echo $record->days_after; ?></td>
<td><?php echo $record->farm_herd; ?></td>
<td><?php echo ($record->disabled != 'Y')?"Disabled":""; ?></td>
</tr>

<?php
}
?>

<tr class="odd">
	<?php echo $form->errorSummary($model); ?>

	<td>
		<?php echo $form->textField($model,'description',array('size'=>25,'maxlength'=>25)); ?>
		<?php echo $form->error($model,'description'); ?>
	</td>

	<td>
		<?php echo $form->textField($model,'times_occur',array('size'=>2,'maxlength'=>2)); ?>
		<?php echo $form->error($model,'times_occur'); ?>
	</td>

	<td>
		<?php echo $form->textField($model,'days_between'); ?>
		<?php echo $form->error($model,'days_between',array('size'=>3,'maxlength'=>3)); ?>
	</td>

	<td>
		<?php echo $form->textField($model,'generated_by',array('size'=>1,'maxlength'=>1)); ?>
		<?php echo $form->error($model,'generated_by'); ?>
	</td>

	<td>
		<?php echo $form->textField($model,'date_asof',array('size'=>10,'maxlength'=>10)); ?>
		<?php echo $form->error($model,'date_asof'); ?>
	</td>

	<td>
		<?php echo $form->textField($model,'days_after',array('size'=>3,'maxlength'=>3)); ?>
		<?php echo $form->error($model,'days_after'); ?>
	</td>

	<td>
		<?php echo $form->textField($model,'farm_herd',array('size'=>2,'maxlength'=>2)); ?>
		<?php echo $form->error($model,'farm_herd'); ?>
	</td>
	<td>
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</td>
</tr>
</tbody>
</table>
</div>
<ul id="menu">
  <li><a href="#"><span class="ui-icon ui-icon-disk"></span>Save</a></li>
  <li><a href="#"><span class="ui-icon ui-icon-zoomin"></span>Zoom In</a></li>
  <li><a href="#"><span class="ui-icon ui-icon-zoomout"></span>Zoom Out</a></li>
  <li class="ui-state-disabled"><a href="#"><span class="ui-icon ui-icon-print"></span>Print...</a></li>
  <li>
    <a href="#">Playback</a>
    <ul>
      <li><a href="#"><span class="ui-icon ui-icon-seek-start"></span>Prev</a></li>
      <li><a href="#"><span class="ui-icon ui-icon-stop"></span>Stop</a></li>
      <li><a href="#"><span class="ui-icon ui-icon-play"></span>Play</a></li>
      <li><a href="#"><span class="ui-icon ui-icon-seek-end"></span>Next</a></li>
    </ul>
  </li>
</ul>
<?php $this->endWidget(); ?>

</div><!-- form -->